### ISSUE TITLE
need help to decrypt api sign auth

### ISSUE THREAD

**Issue by steven7851** [wsguest/DouyuClient#1]
斗鱼网页的flash会使用 http://www.douyu.com/lapi/live/getPlay 来获取直播串流
能否解析出所需的sign算法? 我在src里没看到相关的原码...

**Comment by wsguest** [comment]
留下联系方式发送完整的给你。

**Comment by steven7851** [comment]
steven7851 at gmail.com or QQ1476734933
Thx!
